// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAdWOiBFabCYkKc5IaGth6aLdrgRAnINk',
    appId: '1:46936126497:android:17542d45da733854411f60',
    messagingSenderId: '46936126497',
    projectId: 'dsfulfill-damin-app',
    databaseURL: 'https://dsfulfill-damin-app-default-rtdb.firebaseio.com',
    storageBucket: 'dsfulfill-damin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS6MGm2m8Y9-7UJnwvWywcEJx4hzpTvn0',
    appId: '1:46936126497:ios:d50b7d78695a025e411f60',
    messagingSenderId: '46936126497',
    projectId: 'dsfulfill-damin-app',
    databaseURL: 'https://dsfulfill-damin-app-default-rtdb.firebaseio.com',
    storageBucket: 'dsfulfill-damin-app.firebasestorage.app',
    androidClientId:
        '46936126497-7l9u8gsphrtbkur7sgmgfanu1t00qg81.apps.googleusercontent.com',
    iosClientId:
        '46936126497-ul8fu94s1l0jt3d6r53sb0cpug5i9lle.apps.googleusercontent.com',
    iosBundleId: 'dsfulfill.com',
  );
}
