import 'package:get/get.dart';

class I10N extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'zh_CN': {
          '注册 DSFulfill': '注册 DSFulfill',
          "手机号/邮箱": "手机号/邮箱",
          "密码": "密码",
          "登录": "登录",
          "忘记密码?": "忘记密码?",
          "还没有账号?": "还没有账号?",
          "立即注册": "立即注册",
          "登录 DSFulfill": "登录 DSFulfill",
          "开启您的代发货服务商之旅": "开启您的代发货服务商之旅",
          "邮箱验证码": "邮箱验证码",
          "获取验证码": "获取验证码",
          "阅读并同意": "阅读并同意",
          "DSFulfill条款与条件": "DSFulfill条款与条件",
          "立即登录": "立即登录",
          "请输入邮箱": "请输入邮箱",
          "请输入手机号": "请输入手机号",
          "请输入验证码": "请输入验证码",
          "订单总数": "订单总数",
          "商品总数": "商品总数",
          "物流渠道": "物流渠道",
          "请先登录": "请先登录",
          "加载中": "加载中",
          "加载失败": "加载失败",
          "加载更多": "加载更多",
          "没有更多数据": "没有更多数据",
          "空闲": "空闲",
          "产品规格": "产品规格",
          "产品报价": "产品报价",
          "采购价": "采购价",
          "产品重量": "产品重量",
          "产品尺寸": "产品尺寸",
          "批量编辑": "批量编辑",
          "说明": "说明",
          "利润": "利润",
          "成本": "成本",
          "请输入": "请输入",
          "编辑报价": "编辑报价",
          "请选择分类": "请选择分类",
          "请选择供应商": "请选择供应商",
          "请选择语言": "请选择语言",
          "请输入产品链接": "请输入产品链接",
          "请输入利润": "请输入利润",
          "提交": "提交",
          "提交成功": "提交成功",
          "提交失败": "提交失败",
          "请选择产品分类": "请选择产品分类",
          "请选择产品供应商": "请选择产品供应商",
          "请选择产品语言": "请选择产品语言",
          "请选择产品链接": "请选择产品链接",
          "请输入产品重量": "请输入产品重量",
          "件": "件",
          "筛选": "筛选",
          "订单列表": "订单列表",
          "平台编号": "平台编号",
          "平台SKU": "平台SKU",
          "物流单号": "物流单号",
          "客户": "客户",
          "物流轨迹状态": "物流轨迹状态",
          "国家": "国家",
          "请选择": "请选择",
          "店铺": "店铺",
          "平台": "平台",
          "物流轨迹": "物流轨迹",
          "时间": "时间",
          "查询": "查询",
          "重置": "重置",
          "请选择时间": "请选择时间",
          "确定": "确定",
          "取消": "取消",
          "交运": "交运",
          "退款": "退款",
          "营业情况": "营业情况",
          "订单收入": "订单收入",
          "商品成本": "商品成本",
          "物流成本": "物流成本",
          "我的任务": "我的任务",
          "待报价": "待报价",
          "待申请运单": "待申请运单",
          "待配货": "待配货",
          "异常订单": "异常订单",
          "邀请客户使用": "邀请客户使用",
          "点击右侧复制邀请码，分享链接给您的客户。": "点击右侧复制邀请码，分享链接给您的客户。",
          "首页": "首页",
          "工作台": "工作台",
          "分析": "分析",
          "我的": "我的",
          "产品": "产品",
          "订单": "订单",
          "财务": "财务",
          "产品管理": "产品管理",
          "产品采集": "产品采集",
          "代发订单": "代发订单",
          "转账充值": "转账充值",
          "在线充值": "在线充值",
          "交易流水": "交易流水",
          "客户管理": "客户管理",
          "客户店铺": "客户店铺",
          "商品名称": "商品名称",
          "全部": "全部",
          "待审核": "待审核",
          "审核通过": "审核通过",
          "报价": "报价",
          "长": "长",
          "宽": "宽",
          "高": "高",
          "重量": "重量",
          "颜色": "颜色",
          "尺码": "尺码",
          "请输入完整信息": "请输入完整信息",
          "产品链接": "产品链接",
          "采集产品": "采集产品",
          "产品分类": "产品分类",
          "供应商": "供应商",
          "产品重量必须大于0": "产品重量必须大于0",
          "请输入有效的产品重量": "请输入有效的产品重量",
          "选择产品分类": "选择产品分类",
          "正在加载分类数据": "正在加载分类数据",
          "暂无分类数据": "暂无分类数据",
          "重新加载": "重新加载",
          "暂无二级分类": "暂无二级分类",
          "报价中": "报价中",
          "已报价": "已报价",
          "已付款": "已付款",
          "配货中": "配货中",
          "已出库": "已出库",
          "有异常": "有异常",
          "未查询": "未查询",
          "查询不到": "查询不到",
          "包裹揽收": "包裹揽收",
          "运输途中": "运输途中",
          "运输过久": "运输过久",
          "到达代取": "到达代取",
          "派送途中": "派送途中",
          "投递失败": "投递失败",
          "成功签收": "成功签收",
          "可能异常": "可能异常",
          "创建时间": "创建时间",
          "更新时间": "更新时间",
          "付款时间": "付款时间",
          "交运时间": "交运时间",
          "发货时间": "发货时间",
          "订单详情": "订单详情",
          "订单报价": "订单报价",
          "异常提醒": "异常提醒",
          "知道了": "知道了",
          "异常处理": "异常处理",
          "移入报价中": "移入报价中",
          "重新获取运单号": "重新获取运单号",
          "取消并退款": "取消并退款",
          "忽略异常": "忽略异常",
          "打回报价已支付的款项将自动退回，确定吗？": "打回报价已支付的款项将自动退回，确定吗？",
          "确认取消订单吗？": "确认取消订单吗？",
          "确认": "确认",
          "取消订单": "取消订单",
          "确认取消": "确认取消",
          "确认取消订单并退款吗？": "确认取消订单并退款吗？",
          "报关": "报关",
          "日志": "日志",
          "暂无日志": "暂无日志",
          "商品总报价": "商品总报价",
          "物流总报价": "物流总报价",
          "折扣优惠": "折扣优惠",
          "其他补收": "其他补收",
          "合计": "合计",
          "关联": "关联",
          "数量": "数量",
          "改价": "改价",
          "匹配本地产品": "匹配本地产品",
          "库存消耗": "库存消耗",
          "匹配物流渠道": "匹配物流渠道",
          "报价核对": "报价核对",
          "报价人": "报价人",
          "请选择报价人": "请选择报价人",
          "商品总价": "商品总价",
          "物流总价": "物流总价",
          "其他补价": "其他补价",
          "(人工操作费)": "(人工操作费)",
          "请输入金额": "请输入金额",
          "未关联sku": "未关联sku",
          "本企业": "本企业",
          "客户库存": "客户库存",
          "选择产品": "选择产品",
          "从1688采集": "从1688采集",
          "请选择商品": "请选择商品",
          "已选择": "已选择",
          "处理异常": "处理异常",
          "流水号": "流水号",
          "状态": "状态",
          "转账支付详情": "转账支付详情",
          "审核拒绝": "审核拒绝",
          "客户信息": "客户信息",
          "客户ID": "客户ID",
          "客户名称": "客户名称",
          "支付信息": "支付信息",
          "支付账号": "支付账号",
          "支付金额": "支付金额",
          "客户截图": "客户截图",
          "确认支付信息": "确认支付信息",
          "备注": "备注",
          "收款截图": "收款截图",
          "确认支付": "确认支付",
          "审核拒绝信息": "审核拒绝信息",
          "充值金额": "充值金额",
          "审核": "审核",
          "转账支付": "转账支付",
          "确认金额": "确认金额",
          "图片说明": "图片说明",
          "相册": "相册",
          "相机": "相机",
          "操作成功": "操作成功",
          "支付方式": "支付方式",
          "提交时间": "提交时间",
          "未核账": "未核账",
          "已核账": "已核账",
          "请输入外部交易号": "请输入外部交易号",
          "增加": "增加",
          "减少": "减少",
          "交易详情": "交易详情",
          "关联单号": "关联单号",
          "外部交易号": "外部交易号",
          "客户列表": "客户列表",
          "余额": "余额",
          "剩余额度": "剩余额度",
          "客户昵称": "客户昵称",
          "手机号": "手机号",
          "邮箱": "邮箱",
          "搜索类型": "搜索类型",
          "搜索内容": "搜索内容",
          "客户组": "客户组",
          "员工": "员工",
          "客户详情": "客户详情",
          "修改客户信息": "修改客户信息",
          "用户名": "用户名",
          "请输入用户名": "请输入用户名",
          "电话": "电话",
          "请选择分组": "请选择分组",
          "佣金比例": "佣金比例",
          "调整信用额度": "调整信用额度",
          "原信用额度": "原信用额度",
          "调整后额度": "调整后额度",
          "请输入新额度": "请输入新额度",
          "注册时间": "注册时间",
          "最后登录时间": "最后登录时间",
          "账户信息": "账户信息",
          "消费总额": "消费总额",
          "信用额度": "信用额度",
          "自动支付": "自动支付",
          "修改": "修改",
          "请输入佣金比例": "请输入佣金比例",
          "请输入佣金金额": "请输入佣金金额",
          "数据分析": "数据分析",
          "出库订单": "出库订单",
          "请登录": "请登录",
          "管理员": "管理员",
          "专属客户端": "专属客户端",
          "域名": "域名",
          "品牌": "品牌",
          "预览": "预览",
          "前往电脑版": "前往电脑版",
          "教程中心": "教程中心",
          "修改密码": "修改密码",
          "退出登录": "退出登录",
          "选择团队": "选择团队",
          "你已加入以下团队": "你已加入以下团队",
          "暂无团队": "暂无团队",
          "创建新团队": "创建新团队",
          "创建属于你的团队": "创建属于你的团队",
          "创建团队": "创建团队",
          "创建您的团队": "创建您的团队",
          "团队名称": "团队名称",
          "请输入团队名称": "请输入团队名称",
          "创建专属客户端": "创建专属客户端",
          "客户端设置": "客户端设置",
          "品牌名称": "品牌名称",
          "请输入品牌名称": "请输入品牌名称",
          "品牌LOGO": "品牌LOGO",
          "站点图标": "站点图标",
          "品牌LOGO是您的客户端页面左上角显示的LOGO，它应为长方形，像素至少为154 x 37。":
              "品牌LOGO是您的客户端页面左上角显示的LOGO，它应为长方形，像素至少为154 x 37。",
          "网站图标是您在浏览器标签页、书签栏和 WordPress 移动应用程序中看到的图标。它应为正方形，推荐尺寸为 32 × 32。":
              "网站图标是您在浏览器标签页、书签栏和 WordPress 移动应用程序中看到的图标。它应为正方形，推荐尺寸为 32 × 32。",
          "账号": "账号",
          "请输入账号": "请输入账号",
          "验证码": "验证码",
          "新密码": "新密码",
          "请输入新密码": "请输入新密码",
          "确认密码": "确认密码",
          "请输入确认密码": "请输入确认密码",
          "注意事项": "注意事项",
          "请输入8-16位，且带有 字母、数字、特殊符号三种字符组合的密码！":
              "请输入8-16位，且带有 字母、数字、特殊符号三种字符组合的密码！",
          "两次密码不一致": "两次密码不一致",
          "专为 Dropshipping 履约服务商，重新设计Dropshipping agent 系统":
              "专为 Dropshipping 履约服务商，重新设计Dropshipping agent 系统",
          "DSFulfill 是什么": "DSFulfill 是什么",
          "DSFulfill 为 Dropshipping agent 提供一站式软件管理服务，一套系统从履约、报价、仓储、物流、帐单都能轻松解决":
              "DSFulfill 为 Dropshipping agent 提供一站式软件管理服务，一套系统从履约、报价、仓储、物流、帐单都能轻松解决",
          "自动生成客户端": "自动生成客户端",
          "自动为您生成个性化域名的客户端，Dropshipper通过客户端可以进行自助绑定店铺、同步网店订单、铺货到众多网店平台、发起寻源代采、物流轨迹查询、查询帐单、切换多语言模式等操作":
              "自动为您生成个性化域名的客户端，Dropshipper通过客户端可以进行自助绑定店铺、同步网店订单、铺货到众多网店平台、发起寻源代采、物流轨迹查询、查询帐单、切换多语言模式等操作",
          "专业的管理端": "专业的管理端",
          "0 门槛使用、专为Dropshipping agent而生": "0 门槛使用、专为Dropshipping agent而生",
          "下一步": "下一步",
          "开始体验": "开始体验",
          "已有账户?": "已有账户?",
          "这里登录": "这里登录",
          "转到dsfulfill网页": "转到dsfulfill网页",
          "转到dsfulfill网页。在电脑端访问网页(erp.dsfulfill.com)可以更加方便的进行管理。":
              "转到dsfulfill网页。在电脑端访问网页(erp.dsfulfill.com)可以更加方便的进行管理。",
        },
        'en_US': {
          '注册 DSFulfill': 'Register DSFulfill',
          "手机号/邮箱": "Phone/Email",
          "密码": "Password",
          "登录": "Login",
          "忘记密码?": "Forget Password?",
          "还没有账号?": "Don't have an account?",
          "立即注册": "Register",
          "登录 DSFulfill": "Login DSFulfill",
          "开启您的代发货服务商之旅": "Start your drop shipping service provider journey",
          "邮箱验证码": "Email Verification Code",
          "获取验证码": "Get Verification Code",
          "阅读并同意": "Read and agree",
          "DSFulfill条款与条件": "DSFulfill Terms and Conditions",
          "立即登录": "Login",
          "请输入邮箱": "Please enter email",
          "请输入手机号": "Please enter phone number",
          "请输入验证码": "Please enter verification code",
          "订单总数": "Order Total",
          "商品总数": "Goods Total",
          "物流渠道": "Express Lines",
          "请先登录": "Please log in first.",
          "加载中": "Loading",
          "加载失败": "Load failed",
          "加载更多": "Load more",
          "没有更多数据": "No more data",
          "空闲": "Idle",
          "产品规格": "Product Specification",
          "产品报价": "Product Quote",
          "采购价": "Purchase Price",
          "产品重量": "Product Weight",
          "产品尺寸": "Product Size",
          "批量编辑": "Batch Edit",
          "说明": "Description",
          "编辑报价": "Edit Quote",
          "请选择产品分类": "Please select product category",
          "请输入利润": "Please enter profit",
          "提交": "Submit",
          "提交成功": "Submit successfully",
          "提交失败": "Submit failed",
          "请选择产品供应商": "Please select product supplier",
          "请选择产品语言": "Please select product language",
          "请选择产品链接": "Please select product link",
          "请输入产品重量": "Please enter product weight",
          "件": "Piece",
          "筛选": "Filter",
          "订单列表": "Order List",
          "平台编号": "Platform ID",
          "平台SKU": "Platform SKU",
          "物流单号": "Logistics Number",
          "客户": "Customer",
          "物流轨迹状态": "Logistics Status",
          "国家": "Country",
          "请选择": "Please select",
          "店铺": "Shop",
          "平台": "Platform",
          "物流轨迹": "Logistics Track",
          "时间": "Time",
          "查询": "Search",
          "重置": "Reset",
          "请选择时间": "Please select time",
          "确定": "Confirm",
          "取消": "Cancel",
          "交运": "Shipment",
          "退款": "Refund",
          "营业情况": "Business Situation",
          "订单收入": "Order Income",
          "商品成本": "Goods Cost",
          "物流成本": "Logistics Cost",
          "利润": "Profit",
          "我的任务": "My Tasks",
          "待报价": "Pending Quotes",
          "待申请运单": "Pending Shipment Requests",
          "待配货": "Pending Picking",
          "异常订单": "Abnormal Orders",
          "邀请客户使用": "Invite customers to use",
          "点击右侧复制邀请码，分享链接给您的客户。":
              "Click the right side to copy the invitation code and share the link with your customers.",
          "首页": "Home",
          "工作台": "Dashboard",
          "分析": "Analysis",
          "我的": "My",
          "产品": "Product",
          "订单": "Order",
          "财务": "Finance",
          "产品管理": "Product Management",
          "产品采集": "Product Collection",
          "代发订单": "Drop Shipping Orders",
          "转账充值": "Transfer Recharge",
          "在线充值": "Online Recharge",
          "交易流水": "Transaction Flow",
          "客户管理": "Customer Management",
          "客户店铺": "Customer Shop",
          "商品名称": "Product Name",
          "全部": "All",
          "待审核": "Pending Review",
          "审核通过": "Approved",
          "报价": "Quote",
          "成本": "Cost",
          "请输入": "Please enter",
          "长": "Length",
          "宽": "Width",
          "高": "Height",
          "重量": "Weight",
          "颜色": "Color",
          "尺码": "Size",
          "请输入完整信息": "Please enter complete information",
          "产品链接": "Product Link",
          "采集产品": "Collect Product",
          "产品分类": "Product Category",
          "供应商": "Supplier",
          "产品重量必须大于0": "Product weight must be greater than 0",
          "请输入有效的产品重量": "Please enter a valid product weight",
          "请输入产品链接": "Please enter product link",
          "选择产品分类": "Select Product Category",
          "正在加载分类数据": "Loading category data",
          "暂无分类数据": "No category data",
          "重新加载": "Reload",
          "暂无二级分类": "No sub-category data",
          "报价中": "Quoting",
          "已报价": "Quoted",
          "已付款": "Paid",
          "配货中": "Picking",
          "已出库": "Shipped",
          "有异常": "Exception",
          "未查询": "Not found",
          "查询不到": "Not found",
          "包裹揽收": "Package collected",
          "运输途中": "In transit",
          "运输过久": "Transportation overdue",
          "到达代取": "Arrived for collection",
          "派送途中": "Delivery in progress",
          "投递失败": "Delivery failed",
          "成功签收": "Successfully received",
          "可能异常": "Possible exception",
          "创建时间": "Created time",
          "更新时间": "Updated time",
          "付款时间": "Payment time",
          "交运时间": "Shipment time",
          "发货时间": "Delivery time",
          "订单详情": "Order Details",
          "订单报价": "Order Quote",
          "异常提醒": "Abnormal Reminder",
          "知道了": "I know",
          "异常处理": "Abnormal Handling",
          "移入报价中": "Move to quote",
          "重新获取运单号": "Re-get logistics number",
          "取消并退款": "Cancel and refund",
          "忽略异常": "Ignore exception",
          "打回报价已支付的款项将自动退回，确定吗？":
              "The payment for the quoted order will be automatically refunded, are you sure?",
          "确认取消订单吗？": "Are you sure you want to cancel the order?",
          "确认取消订单并退款吗？":
              "Are you sure you want to cancel the order and refund?",
          "确认": "Confirm",
          "报关": "Customs Declaration",
          "日志": "Log",
          "暂无日志": "No log",
          "商品总报价": "Total goods quote",
          "物流总报价": "Total logistics quote",
          "折扣优惠": "Discount",
          "其他补收": "Other",
          "合计": "Total",
          "关联": "Related",
          "数量": "Quantity",
          "改价": "Edit price",
          "匹配本地产品": "Match local product",
          "库存消耗": "Inventory consumption",
          "匹配物流渠道": "Match logistics channel",
          "报价核对": "Quote verification",
          "报价人": "Quote person",
          "请选择报价人": "Please select quote person",
          "商品总价": "Total goods price",
          "物流总价": "Total logistics price",
          "其他补价": "Other",
          "(人工操作费)": "(Manual operation fee)",
          "请输入金额": "Please enter amount",
          "未关联sku": "Unrelated sku",
          "本企业": "This company",
          "客户库存": "Customer inventory",
          "选择产品": "Select product",
          "从1688采集": "Collect from 1688",
          "请选择商品": "Please select product",
          "已选择": "Selected",
          "处理异常": "Handle exception",
          "流水号": "Serial number",
          "状态": "Status",
          "转账支付详情": "Transfer payment details",
          "审核拒绝": "Audit rejected",
          "客户信息": "Customer information",
          "客户ID": "Customer ID",
          "客户名称": "Customer name",
          "支付信息": "Payment information",
          "支付账号": "Payment account",
          "支付金额": "Payment amount",
          "客户截图": "Customer screenshot",
          "确认支付信息": "Confirm payment information",
          "备注": "Remark",
          "收款截图": "Receipt screenshot",
          "确认支付": "Confirm payment",
          "审核拒绝信息": "Audit rejection information",
          "充值金额": "Recharge amount",
          "审核": "Audit",
          "转账支付": "Transfer payment",
          "确认金额": "Confirm amount",
          "图片说明": "Image description",
          "相册": "Gallery",
          "相机": "Camera",
          "操作成功": "Operation successful",
          "支付方式": "Payment method",
          "提交时间": "Submit time",
          "未核账": "Unaudited",
          "已核账": "Audited",
          "请输入外部交易号": "External transaction number",
          "增加": "Increase",
          "减少": "Decrease",
          "交易详情": "Transaction details",
          "关联单号": "Related order number",
          "外部交易号": "External transaction number",
          "客户列表": "Customer list",
          "余额": "Balance",
          "剩余额度": "Remaining credit",
          "客户昵称": "Customer nickname",
          "手机号": "Phone number",
          "邮箱": "Email",
          "搜索类型": "Search type",
          "搜索内容": "Search content",
          "客户组": "Customer group",
          "员工": "Employee",
          "客户详情": "Customer details",
          "修改客户信息": "Modify customer",
          "用户名": "Username",
          "请输入用户名": "Please enter username",
          "电话": "Phone",
          "请选择分组": "Please select group",
          "佣金比例": "Commission ratio",
          "调整信用额度": "Adjust credit limit",
          "原信用额度": "Original credit limit",
          "调整后额度": "Adjusted credit limit",
          "请输入新额度": "Please enter new limit",
          "注册时间": "Registration time",
          "最后登录时间": "Last login time",
          "账户信息": "Account information",
          "消费总额": "Total consumption",
          "信用额度": "Credit limit",
          "自动支付": "Auto payment",
          "修改": "Modify",
          "请输入佣金比例": "Please enter commission ratio",
          "请输入佣金金额": "Please enter commission amount",
          "数据分析": "Data analysis",
          "出库订单": "Outbound order",
          "请登录": "Please login",
          "管理员": "Admin",
          "专属客户端": "Exclusive client",
          "域名": "Domain",
          "品牌": "Brand",
          "预览": "Preview",
          "前往电脑版": "Go to computer version",
          "教程中心": "Tutorial center",
          "修改密码": "Modify password",
          "退出登录": "Logout",
          "选择团队": "Select team",
          "你已加入以下团队": "You have joined the following teams",
          "暂无团队": "No team",
          "创建新团队": "Create new team",
          "创建属于你的团队": "Create your own team",
          "创建团队": "Create team",
          "创建您的团队": "Create your team",
          "团队名称": "Team name",
          "请输入团队名称": "Please enter team name",
          "创建专属客户端": "Create exclusive client",
          "客户端设置": "Client settings",
          "品牌名称": "Brand name",
          "请输入品牌名称": "Please enter brand name",
          "品牌LOGO": "Brand logo",
          "站点图标": "Site icon",
          "品牌LOGO是您的客户端页面左上角显示的LOGO，它应为长方形，像素至少为154 x 37。":
              "The brand logo is the logo displayed at the top left of your client page, it should be a rectangle, at least 154 x 37 pixels.",
          "网站图标是您在浏览器标签页、书签栏和 WordPress 移动应用程序中看到的图标。它应为正方形，推荐尺寸为 32 × 32。":
              "The website icon is the icon you see in the browser tab, bookmark bar, and WordPress mobile application. It should be a square, recommended size is 32 × 32.",
          "账号": "Account",
          "请输入账号": "Please enter account",
          "验证码": "Verification code",
          "新密码": "New password",
          "请输入新密码": "Please enter new password",
          "确认密码": "Confirm password",
          "请输入确认密码": "Please enter confirm password",
          "注意事项": "Note",
          "请输入8-16位，且带有 字母、数字、特殊符号三种字符组合的密码！":
              "Please enter a password of 8-16 characters, including letters, numbers, and special characters.",
          "两次密码不一致": "Two passwords do not match",
          "专为 Dropshipping 履约服务商，重新设计Dropshipping agent 系统":
              "Empowering Dropshipping Agents With Seamless SaaS Solutions",
          "DSFulfill 是什么": "What is DSFulfill?",
          "DSFulfill 为 Dropshipping agent 提供一站式软件管理服务，一套系统从履约、报价、仓储、物流、帐单都能轻松解决":
              "DSFulfill is a management system tailored for dropshipping agents and suppliers",
          "自动生成客户端": "DSFulfill Client Portal",
          "自动为您生成个性化域名的客户端，Dropshipper通过客户端可以进行自助绑定店铺、同步网店订单、铺货到众多网店平台、发起寻源代采、物流轨迹查询、查询帐单、切换多语言模式等操作":
              "Designed for e-commerce sellers, serving as a terminal for product listing, selection, order synchronization, and quotation fulfillment.",
          "专业的管理端": "DSFulfill Admin Dashboard",
          "0 门槛使用、专为Dropshipping agent而生":
              "Designed for dropshipping fulfillment service providers, dedicated to managing product quotations, logistics quotations, procurement, and order fulfillment.",
          "下一步": "Next",
          "开始体验": "Start experience",
          "已有账户?": "Already have an account?",
          "这里登录": "Here login",
          "转到dsfulfill网页": "Go to dsfulfill website",
          "转到dsfulfill网页。在电脑端访问网页(erp.dsfulfill.com)可以更加方便的进行管理。":
              "Go to the dsfulfill website. Access the website (erp.dsfulfill.com) on the computer to manage it more conveniently.",
        },
      };
}
